### PR TITLE
added own view for ranking classes

### PR DESCRIPTION
**Pull request by KaiWissel**
Schau bitte mal drüber, ob das vom Grundsatz her so passt.
Außerdem raff ich gerade den TS Error in ResultsClasses.vue nicht. Evtl. hast du da eine Idee.

### CODE REVIEW

**Comment by JEK58** [comment]
A selected ranking class should persists even if the year is changed. Only if the selected class does not exist in a year it should fall back to a default. Otherwise => bad UX 

There is a lot of unnecessary overhead API data just for getting the classes of a year in every network request.

**Comment by KaiWissel** [comment]
> A selected ranking class should persists even if the year is changed. Only if the selected class does not exist in a year it should fall back to a default. Otherwise => bad UX
> 
> There is a lot of unnecessary overhead API data just for getting the classes of a year in every network request.

@JEK58 
Fixed the issuse if year is changed.

I considered to encapsulate the fetching of filterOptions to an composable and store these filterOptions within a cache after the first call. Any thoughts?

**Comment by JEK58** [comment]
> > A selected ranking class should persists even if the year is changed. Only if the selected class does not exist in a year it should fall back to a default. Otherwise => bad UX
> > There is a lot of unnecessary overhead API data just for getting the classes of a year in every network request.
> 
> @JEK58 Fixed the issuse if year is changed.
> 
> I considered to encapsulate the fetching of filterOptions to an composable and store these filterOptions within a cache after the first call. Any thoughts?

I think this is adding too much code and complexity to the client. Why not set up an endpoint that provides every year with its ranking classes? Will reduce code and complexity.

**Comment by KaiWissel** [comment]
> 



> > > A selected ranking class should persists even if the year is changed. Only if the selected class does not exist in a year it should fall back to a default. Otherwise => bad UX
> > > There is a lot of unnecessary overhead API data just for getting the classes of a year in every network request.
> > 
> > 
> > @JEK58 Fixed the issuse if year is changed.
> > I considered to encapsulate the fetching of filterOptions to an composable and store these filterOptions within a cache after the first call. Any thoughts?
> 
> I think this is adding too much code and complexity to the client. Why not set up an endpoint that provides every year with its ranking classes? Will reduce code and complexity.

But why call the API every time for the filterOptions? The call in general is more expensive than the addional data in the response.

**Comment by JEK58** [comment]
> > > > A selected ranking class should persists even if the year is changed. Only if the selected class does not exist in a year it should fall back to a default. Otherwise => bad UX
> > > > There is a lot of unnecessary overhead API data just for getting the classes of a year in every network request.
> > > 
> > > 
> > > @JEK58 Fixed the issuse if year is changed.
> > > I considered to encapsulate the fetching of filterOptions to an composable and store these filterOptions within a cache after the first call. Any thoughts?
> > 
> > 
> > I think this is adding too much code and complexity to the client. Why not set up an endpoint that provides every year with its ranking classes? Will reduce code and complexity.
> 
> But why call the API every time for the filterOptions? The call in general is more expensive than the addional data in the response.

Not every time and not all filter options. Just rankingClasses + years one time when the page is loading. If the year is changed there is no need to call the API again.

**Comment by KaiWissel** [comment]
@JEK58 No with caching 🎉

**Review by JEK58 — APPROVED** [review]

**Comment by KaiWissel** [comment]
https://github.com/XCCup/xccup.net/issues/608

**Pull request merged**
